.TH FETCH 1
.SH NAME
.B sysfetch
\- A super tiny Linux system information fetch script written in BASH.
.SH DESCRIPTION
.IP
sysfetch is a small and fast system properties fetcher. It outputs colors to the titles of the properties via VT100 control sequences, so may not output color in all circumstances.
.SH USAGE
.IP
.B sysfetch
.IP
sysfetch displays the system's Host/Username, Uptime, Operating System, System Architecture, Kernel Version, Virtual Terminal, Shell, Desktop Environment/Window Manager, Desktop Theme, CPU model (and if possible the current CPU frequency.), GPU make and model, Motherboard model, Current Memory usage and maximum, and system swap space used.
.SH "CONTRIBUTING"
.IP
To contribute to sysfetch please visit us at: https://github.com/wick3dr0se/sysfetch. Likewise we have a development discord available here: https://discord.gg/TstuWvDzXr
.SH "ATTRIBUTION"
.IP
Idea by Wick3dr0se, code by the same and the open source community.
.IP
This program is distributed under the GPL-3.0 License.
